version: 2.1

jobs:
  build_doc_r:
    docker:
      - image: ubuntu:16.04

    steps:
      - checkout
      - run:
          name: Install dev tools
          command: |
            apt-get update --yes
            apt-get install sudo git wget curl jq software-properties-common apt-transport-https --yes

      - run:
          name: Install Java
          command: |
            sudo apt-get install default-jdk --yes
            java -version
      - run:
          name: Install R
          command: |
            echo "deb https://cloud.r-project.org/bin/linux/ubuntu xenial-cran35/" | sudo tee -a /etc/apt/sources.list
            sudo add-apt-repository ppa:cran/libgit2 --yes
            sudo apt-get update --yes
            sudo apt-get install --yes --allow-unauthenticated \
              r-base r-base-dev libssl-dev libcurl4-openssl-dev texlive-latex-base libxml2-dev libssh2-1-dev libgit2-dev

      - run:
          name: Install pandoc
          command: |
            # Install a recent version of pandoc
            TEMP_DEB="$(mktemp)"
            wget -O "$TEMP_DEB" 'https://github.com/jgm/pandoc/releases/download/2.7.2/pandoc-2.7.2-1-amd64.deb'
            sudo dpkg -i "$TEMP_DEB"
            rm -f "$TEMP_DEB"

      - run:
          name: Dump R dependencies
          working_directory: mlflow/R/mlflow
          command: |
            Rscript .dump-r-dependencies.R

      - restore_cache:
          keys:
            - r-cache-{{ checksum "mlflow/R/mlflow/R-version" }}

      - run:
          name: Build documentation
          working_directory: docs
          command: |
            ./build-rdoc.sh

      - run:
          name: Check diff
          command: |
            set +e
            git add .
            PATCH_FILE="<< pipeline.git.revision >>.patch"
            git --no-pager diff --cached --exit-code > $PATCH_FILE
            failed=$?

            if [[ "$failed" == "1" ]]; then
              cat $PATCH_FILE
              MLFLOW_REPO_ID=$(curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/mlflow/mlflow | jq '.id')
              PATCH_FILE_URL="https://${CIRCLE_BUILD_NUM}-${MLFLOW_REPO_ID}-gh.circle-artifacts.com/0/${PATCH_FILE}"
              echo "========== Run the following commands to apply the diff above =========="
              echo "PATCH_FILE_URL=\"$PATCH_FILE_URL\""
              echo 'REDIRECTED_URL=$(curl -Ls -o /dev/null -w %{url_effective} $PATCH_FILE_URL)'
              echo 'curl -s $REDIRECTED_URL | git apply --verbose'
              echo "========================================================================"
            fi

            exit $failed

      - save_cache:
          key: r-cache-{{ checksum "mlflow/R/mlflow/R-version" }}-{{ checksum "mlflow/R/mlflow/depends.Rds" }}
          paths:
            - /usr/local/lib/R/site-library

      - store_artifacts:
          path: << pipeline.git.revision >>.patch

  build_doc:
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout
      - run:
          name: Install Java
          command: |
            sudo apt-get update --yes
            sudo apt-get install default-jdk --yes
            sudo apt-get install maven --yes
            java -version
      - run:
          name: Install Python dependencies
          command: |
            pip --version
            pip install --progress-bar off -r dev-requirements.txt .
      - run:
          name: Build documentation
          working_directory: docs
          environment:
            JAVA_HOME: /usr/lib/jvm/default-java
          command: |
            make rsthtml
            make javadocs
      - store_artifacts:
          path: docs/build/html

workflows:
  build:
    jobs:
      - build_doc
      - build_doc_r
