name: UI Bug Report
description: Create a report to help us reproduce and correct the UI bug
labels: ['bug', 'area/uiux']
title: '[BUG]'

body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for additional information about bug reports. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).
        #### Please fill in this UI bug report template to ensure a timely and thorough response.
  - type: dropdown
    id: contribution
    attributes:
      label: Willingness to contribute
      description: The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?
      options:
        - Yes. I can contribute a fix for this bug independently.
        - Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
        - No. I cannot contribute a bug fix at this time.
    validations:
      required: true

  - type: textarea
    validations:
      required: true
    attributes:
      label: System information
      description: |
        Describe the system where you encountered the bug.
      value: |
        - **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
        - **MLflow version (run `mlflow --version`) or commit SHA if you have MLflow installed from source (run `pip freeze | grep mlflow`)**:
        - **Python version**:
        - **yarn version, if running the dev UI**:

  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the problem
      description: |
        Describe the problem clearly here. Include descriptions of the expected behavior and the actual behavior.

  - type: textarea
    validations:
      required: true
    attributes:
      label: Steps to reproduce the bug
      description: |
        **Record** steps to reproduce the bug as a video or GIF and attach it here.

  - type: textarea
    attributes:
      label: Code to generate data required to reproduce the bug
      description: |
        Please provide code to generate data required to reproduce the bug.
      placeholder: |
        ```python
        import mlflow

        with mlflow.start_run():
            mlflow.log_param("p", 0)
            mlflow.log_metric("m", 1)
        ```

  - type: textarea
    attributes:
      label: Is the console panel showing errors relevant to the bug?
      description: |
        If the console panel in your browser's DevTools is showing errors (displayed in red) relevant to the bug as shown in the screenshot below, please provide them as text or a screenshot.

        #### Instructions on how to use DevTools:
        - Chrome: [Chrome DevTools](https://developer.chrome.com/docs/devtools/)
        - Firefox: [Firefox DevTools User Docs](https://firefox-source-docs.mozilla.org/devtools-user/index.html)
        - Edge: [Overview of DevTools](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/overview)

        ![console-panel](https://github.com/mlflow/mlflow/blob/master/.github/ISSUE_TEMPLATE/images/console-panel.png?raw=true)
        <p align="center">Console panel on Chrome</P>

  - type: textarea
    attributes:
      label: Does the network panel contain failed requests relevant to the bug?
      description: |
        If the network panel in your browser's DevTools contain failed requests (displayed in red) relevant to the bug as shown in the screenshot below, provide them as text or a screenshot.

        ![network-panel](https://github.com/mlflow/mlflow/blob/master/.github/ISSUE_TEMPLATE/images/network-panel.png?raw=true)
        <p align="center">Network panel on Chrome</P>
