channels:
- conda-forge
dependencies:
- python=3.8.2
- pip
- pip:
  - mlflow
  - torchvision>=0.9.1
  # Avoid using torchmetrics 0.6.0 due to https://github.com/PyTorchLightning/pytorch-lightning/discussions/10253
  - torchmetrics!=0.6.0
  - cloudpickle==1.6.0
  - pytorch_lightning==1.4.9
  - ax-platform
  - prettytable
  - torch>=1.9.0
